function s = defaults(section)
%defaults  Default settings of one config section (schema v1).
%   S = EphysPipelineConfig.defaults("Spikes") etc. The defaults are the
%   single source of truth for field names, types and shapes: normalizeSection
%   coerces every assigned value to match them.
%
%   Continuous-signal defaults mirror EphysDataset.deriveSignals; detection
%   defaults mirror EphysDataset.detectSpikes; the artifact and SpikeInterface
%   defaults come from EphysDataset.defaultArtifactConfig / defaultSIConfig.

arguments
    section (1,1) string
end

switch section
    case "Project"
        s = struct( ...
            'Root',       "", ...            % folder scanned for recordings
            'OutputRoot', "", ...            % "" = outputs next to each recording
            'Selection',  "all", ...         % "all" | "list"
            'Datasets',   string.empty(1,0)); % root-relative keys when "list"

    case "Probe"
        s = struct( ...
            'DefaultProbeFile',       "", ...  % assigned to datasets without a probe
            'WriteDefaultToManifest', false);

    case "Behavior"
        s = struct( ...
            'Enabled',           false, ...
            'SearchDirs',        string.empty(1,0), ...
            'Match',             "prefix-then-time", ...  % "prefix" | "time" | "prefix-then-time"
            'MaxStartOffsetMin', 30, ...
            'Overwrite',         false);      % re-match datasets that already have a file

    case "Artifacts"
        a = EphysDataset.defaultArtifactConfig();
        s = struct( ...
            'Enabled',        false, ...       % automatic detection (manual periods always apply)
            'Method',         a.Method, ...
            'Threshold',      a.Threshold, ...
            'RmsWindowMs',    a.RmsWindowMs, ...
            'MergeGapMs',     a.MergeGapMs, ...
            'MinChannels',    a.MinChannels, ...
            'PadMs',          a.PadMs, ...
            'Filter',         a.Filter, ...
            'FilterType',     a.FilterType, ...
            'FilterCutoff',   a.FilterCutoff, ...
            'FilterOrder',    a.FilterOrder, ...
            'ApplyToSorting', true, ...
            'ApplyToSpikes',  true, ...
            'CacheIntervals', true);

    case "Sorting"
        ks4 = struct();
        spec = EphysPipelineConfig.kilosortParamSpec();
        for i = 1:numel(spec)
            ks4.(spec(i).name) = ks4Default(spec(i));
        end
        s = struct( ...
            'Enabled',      false, ...
            'PythonExe',    "", ...
            'CondaEnv',     "", ...
            'Execution',    "background", ...  % "background" | "blocking"
            'DryRun',       false, ...
            'SkipExisting', false, ...          % skip datasets that already have results
            'SI',           EphysDataset.defaultSIConfig(), ...
            'KS4',          ks4, ...
            'KS4ExtraJSON', "");

    case "Signals"
        s = struct( ...
            'Enabled',            false, ...
            'OutputDir',          "", ...
            'Suffix',             "_extract", ...
            'MatVersion',         "-v7.3", ...
            'Overwrite',          false, ...
            'LFP',                true, ...
            'MUA',                false, ...
            'SPIKE',              false, ...
            'LFP_Fs',             1000, ...
            'LFP_HighpassOn',     false, ...
            'LFP_HighpassHz',     1, ...
            'LFP_LowpassOn',      false, ...
            'LFP_LowpassHz',      300, ...
            'LFP_NotchOn',        false, ...
            'LFP_NotchHz',        "60", ...    % list text, e.g. "60, 120, 180"
            'LFP_NotchBW',        2, ...
            'MUA_Fs',             2000, ...
            'MUA_IntegrationHz',  1000, ...
            'MUA_bpLoHi',         [300 5000], ...
            'SPIKE_KeepOriginal', true, ...
            'SPIKE_Fs',           20000, ...   % used only when KeepOriginal is off
            'SPIKE_bpLoHi',       [300 5000], ...
            'LabelField',         "custom_channel_name", ...
            'KeepChannels',       "", ...
            'BadMode',            "none", ...  % "none" | "manual" | "auto"
            'BadThreshold',       3, ...
            'BadList',            "", ...
            'ChannelRemap',       "", ...
            'ExcludeHandling',    "none", ...  % "none" | "drop" | "interpolate" (manifest exclusions)
            'IncludeBehavior',    true);

    case "Spikes"
        s = struct( ...
            'Enabled',         false, ...
            'Source',          "detect", ...   % "detect" | "sorted" | "both"
            'Filter',          true, ...
            'Band',            [500 5000], ...
            'FilterOrder',     4, ...
            'Polarity',        "negative", ...
            'ThresholdMethod', "mad", ...
            'Threshold',       NaN, ...        % NaN = detectSpikes' default for the method
            'Align',           "trough", ...
            'AlignWindowMs',   1, ...
            'MinPeriodMs',     1, ...
            'MaxAmplitudeUV',  Inf, ...
            'Waveforms',       false, ...
            'WindowMs',        [-0.5 1.5], ...
            'WaveformSource',  "filtered", ...
            'EdgeHandling',    "nan", ...
            'Channels',        "all", ...      % "all" | "excludeManifest" | "list"
            'ChannelList',     "", ...
            'RejectArtifacts', true, ...
            'MaxChunkSamples', NaN, ...
            'EdgePadMs',       NaN, ...
            'UseParallel',     false, ...
            'Groups',          ["good" "mua"], ...
            'IncludeNoise',    false, ...
            'Templates',       true, ...
            'OutputDir',       "", ...
            'Suffix',          "_spikes", ...
            'MatVersion',      "-v7.3", ...
            'Overwrite',       false);

    case "Export"
        s = struct( ...
            'Enabled',         false, ...
            'Formats',         string.empty(1,0), ...   % subset of ["chronux" "fieldtrip"]
            'Signals',         string.empty(1,0), ...   % [] = every signal in the extract
            'IncludeUnits',    true, ...
            'IncludeDetected', false, ...
            'IncludeEvents',   true, ...
            'IncludeBehavior', true, ...
            'Groups',          ["good" "mua"], ...
            'Validate',        true, ...
            'OutputDir',       "", ...
            'MatVersion',      "-v7.3", ...
            'Overwrite',       false);

    otherwise
        error('EphysPipelineConfig:BadSection', 'Unknown section "%s".', section);
end
end


function v = ks4Default(p)
%ks4Default  Typed default of one Kilosort4 parameter (see kilosortParamSpec).
switch p.kind
    case 'bool',     v = logical(p.default);
    case {'int', 'float'}, v = double(p.default);
    case 'floatinf'
        [v, ~] = EphysPipelineConfig.ks4ParamFromText('floatinf', p.default);
    case 'nullable'
        [v, ~] = EphysPipelineConfig.ks4ParamFromText('nullable', p.default);
    case 'vector'
        [v, ~] = EphysPipelineConfig.ks4ParamFromText('vector', p.default);
    otherwise
        v = p.default;
end
end
