function tf = artMarkActive(obj)
    % True when the Mark manual periods view is on screen with a dataset loaded.
    tf = ~isempty(obj.ArtMarkViewer) && isvalid(obj.ArtMarkViewer) ...
        && ~isempty(obj.ArtMarkDataset) && isvalid(obj.ArtMarkDataset) ...
        && isvalid(obj.Fig) && obj.Tabs.SelectedTab == obj.TabArtifacts ...
        && obj.ArtViewTabs.SelectedTab == obj.ArtTabMark;
end
