function savePreferences(obj)
%savePreferences  Persist app preferences (not the pipeline config).
%   See loadPreferences for the list. The config itself is saved through
%   File > Save; only its file name is remembered here.

g = obj.PrefGroup;
if isvalid(obj.Fig)
    setpref(g, 'FigurePosition', obj.Fig.Position);
end
setpref(g, 'ProbeFolder',   char(obj.ProbeFolderField.Value));
setpref(g, 'PhyCmd',        char(obj.PhyCmdField.Value));
setpref(g, 'ReviewFolder',  char(obj.ReviewFolderField.Value));
setpref(g, 'ScriptFolder',  char(obj.ScriptFolder));
setpref(g, 'RecentConfigs', cellstr(obj.RecentConfigs));
setpref(g, 'LastConfigFile', char(obj.Config.File));
order = obj.DatasetsColumnOrder;
T = obj.DatasetsTable.Data;
dco = obj.DatasetsTable.DisplayColumnOrder;
if istable(T) && width(T) > 0 && numel(dco) == width(T)   % dragged since the last refresh
    order = string(T.Properties.VariableNames(dco));
end
setpref(g, 'DatasetsColumnOrder', cellstr(order));
setpref(g, 'TrialsParamColumns', cellstr(obj.TrialsParamColumns));
setpref(g, 'TrialsColumnOrder', cellstr(obj.trialsColumnOrder()));
setpref(g, 'TrialsLabelParams', cellstr(obj.TrialsLabelParams));
setpref(g, 'ShowRunDiagram', logical(obj.RunDiagramCheckBox.Value));
setpref(g, 'DiagramView', char(obj.FlowViewDropDown.Value));
setpref(g, 'DiagramLayout', char(obj.FlowLayoutDropDown.Value));
setpref(g, 'MonitorResources', logical(obj.RunMonitorCheckBox.Value));
setpref(g, 'QueueSortingRuns', logical(obj.RunKSQueueCheckBox.Value));
setpref(g, 'VizOptions', struct( ...
    'source',    char(obj.VizSourceKind), ...
    'channels',  char(obj.VizChannelsField.Value), ...
    'lanes',     obj.VizLanesField.Value, ...
    'duration',  obj.VizDurField.Value, ...
    'highpass',  char(obj.VizHighpassField.Value), ...
    'lowpass',   char(obj.VizLowpassField.Value), ...
    'order',     obj.VizOrderField.Value, ...
    'referenceMode', char(obj.VizRefDropDown.Value), ...
    'removeOffset', logical(obj.VizOffsetCheckBox.Value), ...
    'units',     logical(obj.VizUnitsCheckBox.Value), ...
    'unitStyle', char(obj.VizUnitStyleDropDown.Value), ...
    'unitGroups', char(obj.VizUnitGroupsDropDown.Value), ...
    'detected',  logical(obj.VizDetectedCheckBox.Value), ...
    'detectedStyle', char(obj.VizDetectedStyleDropDown.Value), ...
    'placement', char(obj.VizPlacementDropDown.Value), ...
    'mode',      char(obj.VizModeDropDown.Value), ...
    'colormap',  char(obj.VizColormapDropDown.Value), ...
    'probeOrder', logical(obj.VizSortByProbeCheckBox.Value), ...
    'shankColor', logical(obj.VizColorByShankCheckBox.Value), ...
    'shading',   logical(obj.VizShadingCheckBox.Value), ...
    'events',    char(obj.VizEventsDropDown.Value)));
setpref(g, 'CopyOptions', struct( ...
    'subject',    char(obj.CopySubjectField.Value), ...
    'epsychRoot', char(obj.CopyEpsychRootField.Value), ...
    'recordingRoots', char(obj.CopyRecordingRootsField.Value), ...
    'destRoot',   char(obj.CopyDestRootField.Value), ...
    'maxLeadMin', obj.CopyMaxLeadField.Value, ...
    'maxLagMin',  obj.CopyMaxLagField.Value, ...
    'marginSec',  obj.CopyMarginField.Value, ...
    'minDurationMin', obj.CopyMinDurationField.Value, ...
    'verify',     char(obj.CopyVerifyDropDown.Value), ...
    'ifExists',   char(obj.CopyIfExistsDropDown.Value), ...
    'openAfter',  logical(obj.CopyScanAfterCheckBox.Value)));
design = "";
try design = jsonencode(obj.gatherSynthDesign().toStruct()); catch, end
lines = obj.SynthLinesTable.Data;
if isempty(lines); lines = cell(0, 3); end
setpref(g, 'SynthOptions', struct( ...
    'source',      char(obj.SynthSourceDropDown.Value), ...
    'numTrials',   obj.SynthTrialsSpinner.Value, ...
    'scenario',    char(obj.SynthScenarioDropDown.Value), ...
    'trialDuration', char(obj.SynthTrialDurField.Value), ...
    'lines',       {cellstr(string(lines))}, ...
    'format',      char(obj.SynthFormatDropDown.Value), ...
    'Fs',          obj.SynthFsField.Value, ...
    'numChannels', obj.SynthChannelsField.Value, ...
    'fileSeconds', obj.SynthFileSecondsField.Value, ...
    'maxDuration', obj.SynthMaxDurField.Value, ...
    'seed',        obj.SynthSeedField.Value, ...
    'subject',     char(obj.SynthSubjectField.Value), ...
    'sorted',      logical(obj.SynthSortedCheckBox.Value), ...
    'artifacts',   logical(obj.SynthArtifactsCheckBox.Value), ...
    'output',      char(obj.SynthOutputField.Value), ...
    'span',        obj.SynthTimelineSpanField.Value, ...
    'design',      char(design)));
steps = obj.CleanupStepCheckBoxes;
setpref(g, 'CleanupOptions', struct( ...
    'raw',        logical(obj.CleanupRawCheckBox.Value), ...
    'sorterCopy', logical(obj.CleanupSorterCopyCheckBox.Value), ...
    'bin',        logical(obj.CleanupBinCheckBox.Value), ...
    'steps',      {cellstr(string({steps([steps.Value]).Tag}))}, ...
    'method',     char(obj.CleanupMethodDropDown.Value), ...
    'destination', char(obj.CleanupDestField.Value), ...
    'showKept',   logical(obj.CleanupShowKeptCheckBox.Value)));
end
