function savePreferences(obj)
%savePreferences  Persist app preferences (not the pipeline config).
%   See loadPreferences for the list. The config itself is saved through
%   File > Save; only its file name is remembered here.

g = obj.PrefGroup;
if isvalid(obj.Fig)
    setpref(g, 'FigurePosition', obj.Fig.Position);
end
setpref(g, 'ProbeFolder',   char(obj.ProbeFolderField.Value));
setpref(g, 'PhyCmd',        char(obj.PhyCmdField.Value));
setpref(g, 'ReviewFolder',  char(obj.ReviewFolderField.Value));
setpref(g, 'ScriptFolder',  char(obj.ScriptFolder));
setpref(g, 'RecentConfigs', cellstr(obj.RecentConfigs));
setpref(g, 'LastConfigFile', char(obj.Config.File));
order = obj.DatasetsColumnOrder;
T = obj.DatasetsTable.Data;
dco = obj.DatasetsTable.DisplayColumnOrder;
if istable(T) && width(T) > 0 && numel(dco) == width(T)   % dragged since the last refresh
    order = string(T.Properties.VariableNames(dco));
end
setpref(g, 'DatasetsColumnOrder', cellstr(order));
setpref(g, 'TrialsParamColumns', cellstr(obj.TrialsParamColumns));
setpref(g, 'TrialsColumnOrder', cellstr(obj.trialsColumnOrder()));
setpref(g, 'TrialsLabelParams', cellstr(obj.TrialsLabelParams));
setpref(g, 'VizOptions', struct( ...
    'channels',  char(obj.VizChannelsField.Value), ...
    'duration',  obj.VizDurField.Value, ...
    'highpass',  char(obj.VizHighpassField.Value), ...
    'lowpass',   char(obj.VizLowpassField.Value), ...
    'order',     obj.VizOrderField.Value, ...
    'reference', char(obj.VizRefDropDown.Value), ...
    'detrend',   logical(obj.VizDetrendCheckBox.Value), ...
    'spacing',   obj.VizSpacingField.Value));
setpref(g, 'NasOptions', struct( ...
    'subject',    char(obj.NasSubjectField.Value), ...
    'epsychRoot', char(obj.NasEpsychRootField.Value), ...
    'intanRoot',  char(obj.NasIntanRootField.Value), ...
    'destRoot',   char(obj.NasDestRootField.Value), ...
    'maxLeadMin', obj.NasMaxLeadField.Value, ...
    'maxLagMin',  obj.NasMaxLagField.Value, ...
    'marginSec',  obj.NasMarginField.Value, ...
    'minDurationMin', obj.NasMinDurationField.Value, ...
    'verify',     char(obj.NasVerifyDropDown.Value), ...
    'ifExists',   char(obj.NasIfExistsDropDown.Value), ...
    'openAfter',  logical(obj.NasScanAfterCheckBox.Value)));
end
