function savePreferences(obj)
%savePreferences  Persist app preferences (not the pipeline config).
%   See loadPreferences for the list. The config itself is saved through
%   File > Save; only its file name is remembered here.

g = obj.PrefGroup;
if isvalid(obj.Fig)
    setpref(g, 'FigurePosition', obj.Fig.Position);
end
setpref(g, 'ProbeFolder',   char(obj.ProbeFolderField.Value));
setpref(g, 'PhyCmd',        char(obj.PhyCmdField.Value));
setpref(g, 'ReviewFolder',  char(obj.ReviewFolderField.Value));
setpref(g, 'ScriptFolder',  char(obj.ScriptFolder));
setpref(g, 'RecentConfigs', cellstr(obj.RecentConfigs));
setpref(g, 'LastConfigFile', char(obj.Config.File));
order = obj.DatasetsColumnOrder;
T = obj.DatasetsTable.Data;
dco = obj.DatasetsTable.DisplayColumnOrder;
if istable(T) && width(T) > 0 && numel(dco) == width(T)   % dragged since the last refresh
    order = string(T.Properties.VariableNames(dco));
end
setpref(g, 'DatasetsColumnOrder', cellstr(order));
setpref(g, 'TrialsParamColumns', cellstr(obj.TrialsParamColumns));
setpref(g, 'TrialsColumnOrder', cellstr(obj.trialsColumnOrder()));
setpref(g, 'TrialsLabelParams', cellstr(obj.TrialsLabelParams));
setpref(g, 'ShowRunDiagram', logical(obj.RunDiagramCheckBox.Value));
setpref(g, 'MonitorResources', logical(obj.RunMonitorCheckBox.Value));
setpref(g, 'VizOptions', struct( ...
    'channels',  char(obj.VizChannelsField.Value), ...
    'duration',  obj.VizDurField.Value, ...
    'highpass',  char(obj.VizHighpassField.Value), ...
    'lowpass',   char(obj.VizLowpassField.Value), ...
    'order',     obj.VizOrderField.Value, ...
    'reference', char(obj.VizRefDropDown.Value), ...
    'detrend',   logical(obj.VizDetrendCheckBox.Value), ...
    'spacing',   obj.VizSpacingField.Value));
setpref(g, 'CopyOptions', struct( ...
    'subject',    char(obj.CopySubjectField.Value), ...
    'epsychRoot', char(obj.CopyEpsychRootField.Value), ...
    'recordingRoots', char(obj.CopyRecordingRootsField.Value), ...
    'destRoot',   char(obj.CopyDestRootField.Value), ...
    'maxLeadMin', obj.CopyMaxLeadField.Value, ...
    'maxLagMin',  obj.CopyMaxLagField.Value, ...
    'marginSec',  obj.CopyMarginField.Value, ...
    'minDurationMin', obj.CopyMinDurationField.Value, ...
    'verify',     char(obj.CopyVerifyDropDown.Value), ...
    'ifExists',   char(obj.CopyIfExistsDropDown.Value), ...
    'openAfter',  logical(obj.CopyScanAfterCheckBox.Value)));
setpref(g, 'CleanupOptions', struct( ...
    'raw',        logical(obj.CleanupRawCheckBox.Value), ...
    'sorterCopy', logical(obj.CleanupSorterCopyCheckBox.Value), ...
    'bin',        logical(obj.CleanupBinCheckBox.Value), ...
    'showKept',   logical(obj.CleanupShowKeptCheckBox.Value)));
end
