function showVizHelp(obj)
%showVizHelp  A small window listing the Visualize plot's mouse and key controls.
%   Opened by the "?" button at the end of the Visualize toolbar. It is
%   not modal, so it can stay open beside the plot; pressing the button
%   again brings it to the front, and it closes with the app.
%
%   See also buildVisualizeTab, onVizInput, EphysTraceViewer.handleKey.

h = obj.VizHelpFig;
if ~isempty(h) && isvalid(h)
    figure(h);
    return
end
txt = helpText();
nLines = numel(splitlines(txt));
p = obj.Fig.Position;
w = 470;
ht = 16 * nLines + 24;
h = uifigure("Name", "Visualize: mouse and keys", "Resize", "off", ...
    "Position", [p(1) + p(3) - w - 40, p(2) + p(4) - ht - 90, w, ht]);
g = uigridlayout(h, [1 1]);
g.Padding = [12 12 12 12];
uilabel(g, "Text", txt, "FontName", get(0, 'FixedWidthFontName'), "FontSize", 12, ...
    "VerticalAlignment", "top", "WordWrap", "off");
obj.VizHelpFig = h;
fig = obj.Fig;
addlistener(fig, 'ObjectBeingDestroyed', @(~, ~) closeHelp(h));
end


function closeHelp(h)
if isvalid(h); delete(h); end
end


function s = helpText()
%helpText  The cheatsheet.
s = sprintf([ ...
    'With the pointer over the plot:\n' ...
    '  wheel ............... zoom time about the pointer\n' ...
    '  Ctrl+wheel .......... scale the voltage\n' ...
    '  Shift+wheel ......... scroll the lanes\n' ...
    '  drag ................ pan time (and lanes)\n' ...
    '  <- / -> ............. pan a quarter window\n' ...
    '  Ctrl+<- / -> ........ pan a whole window\n' ...
    '  Shift+<- / -> ....... zoom time out / in\n' ...
    '  Page Up / Down ...... a whole window\n' ...
    '  Up / Down, + / - .... scale the voltage\n' ...
    '  Shift+Up / Down ..... scroll the lanes\n' ...
    '  Home / End .......... start / end\n' ...
    '  A ................... auto scale\n' ...
    '  R ................... reset the view\n' ...
    '\n' ...
    'Overview strip (under the plot, the whole recording):\n' ...
    '  click or drag ....... centre the view there\n' ...
    '\n' ...
    'Mark Artifacts on:\n' ...
    '  drag ................ mark a period\n' ...
    '  click a red period .. remove it\n' ...
    '  right-button drag ... pan\n' ...
    '  Esc ................. stop marking\n' ...
    '\n' ...
    'Events: solid line = onset, dotted = offset;\n' ...
    'TTL rows above the traces are high while a line is on.\n' ...
    'The arrows by the line box (top right) step to the\n' ...
    'line''s previous / next onset.']);
end
