function D = read_Intan_RHD2000_file_modified(ffn,options)

% read_Intan_RHD2000_file_modified
%
% Version 3.0, 8 February 2021
%
% Reads Intan Technologies RHD data file generated by Intan USB interface
% board or Intan Recording Controller.  Data are parsed and placed into
% variables that appear in the base MATLAB workspace.  Therefore, it is
% recommended to execute a 'clear' command before running this program to
% clear all other variables from the base workspace.
%
% Example:
% >> clear
% >> read_Intan_RHD2000_file
% >> whos
% >> amplifier_channels(1)
% >> plot(t_amplifier, amplifier_data(1,:))

% modified by DS 11/2025
%
% Modified for the pipeline (IntanReader):
%   - the data blocks are read with one fread as uint16 words and split
%     into the signals by IntanReader.sliceDataBlocks (the block layout
%     the window reads use too); the values are the same as the original
%     per-block loop gave
%   - only whole data blocks are read: a truncated last block (a recording
%     cut short) is ignored, as IntanReader.parseIntanHeader counts them
%   - the file is closed on every exit path, errors included

arguments
    ffn (1,1) string {mustBeFile}
    options.Verbosity (1,1) string {mustBeMember(options.Verbosity,["silent","high"])} = "high"
end

if isempty(ffn) || ffn == ""
    [file, path, filterindex] = ...
        uigetfile('*.rhd', 'Select an RHD2000 Data File', 'MultiSelect', 'off');

    if (file == 0)
        return;
    end
    ffn = [path,file];

end


tic;
fid = fopen(ffn, 'r');
if fid < 0
    error('read_Intan_RHD2000_file_modified:OpenFailed', 'Could not open %s', ffn);
end
closer = onCleanup(@() fclose(fid));   % closes the file on every exit path

s = dir(ffn);
filesize = s.bytes;

% Check 'magic number' at beginning of file to make sure this is an Intan
% Technologies RHD2000 data file.
magic_number = fread(fid, 1, 'uint32');
if magic_number ~= hex2dec('c6912702')
    error('read_Intan_RHD2000_file_modified:BadMagic', 'Unrecognized file type: %s', ffn);
end

% Read version number.
data_file_main_version_number = fread(fid, 1, 'int16');
data_file_secondary_version_number = fread(fid, 1, 'int16');

if options.Verbosity == "high"
    fprintf(1, '\n');
    fprintf(1, 'Reading Intan Technologies RHD2000 Data File, Version %d.%d\n', ...
        data_file_main_version_number, data_file_secondary_version_number);
    fprintf(1, '\n');
end

if (data_file_main_version_number == 1)
    num_samples_per_data_block = 60;
else
    num_samples_per_data_block = 128;
end

% Read information of sampling rate and amplifier frequency settings.
sample_rate = fread(fid, 1, 'single');
dsp_enabled = fread(fid, 1, 'int16');
actual_dsp_cutoff_frequency = fread(fid, 1, 'single');
actual_lower_bandwidth = fread(fid, 1, 'single');
actual_upper_bandwidth = fread(fid, 1, 'single');

desired_dsp_cutoff_frequency = fread(fid, 1, 'single');
desired_lower_bandwidth = fread(fid, 1, 'single');
desired_upper_bandwidth = fread(fid, 1, 'single');

% This tells us if a software 50/60 Hz notch filter was enabled during
% the data acquisition.
notch_filter_mode = fread(fid, 1, 'int16');
notch_filter_frequency = 0;
if (notch_filter_mode == 1)
    notch_filter_frequency = 50;
elseif (notch_filter_mode == 2)
    notch_filter_frequency = 60;
end

desired_impedance_test_frequency = fread(fid, 1, 'single');
actual_impedance_test_frequency = fread(fid, 1, 'single');

% Place notes in data strucure
notes = struct( ...
    'note1', fread_QString(fid), ...
    'note2', fread_QString(fid), ...
    'note3', fread_QString(fid) );

% If data file is from GUI v1.1 or later, see if temperature sensor data
% was saved.
num_temp_sensor_channels = 0;
if ((data_file_main_version_number == 1 && data_file_secondary_version_number >= 1) ...
        || (data_file_main_version_number > 1))
    num_temp_sensor_channels = fread(fid, 1, 'int16');
end

% If data file is from GUI v1.3 or later, load board mode.
board_mode = 0;
if ((data_file_main_version_number == 1 && data_file_secondary_version_number >= 3) ...
        || (data_file_main_version_number > 1))
    board_mode = fread(fid, 1, 'int16');
end

% If data file is from v2.0 or later (Intan Recording Controller),
% load name of digital reference channel.
if (data_file_main_version_number > 1)
    reference_channel = fread_QString(fid);
end

% Place frequency-related information in data structure.
frequency_parameters = struct( ...
    'amplifier_sample_rate', sample_rate, ...
    'aux_input_sample_rate', sample_rate / 4, ...
    'supply_voltage_sample_rate', sample_rate / num_samples_per_data_block, ...
    'board_adc_sample_rate', sample_rate, ...
    'board_dig_in_sample_rate', sample_rate, ...
    'desired_dsp_cutoff_frequency', desired_dsp_cutoff_frequency, ...
    'actual_dsp_cutoff_frequency', actual_dsp_cutoff_frequency, ...
    'dsp_enabled', dsp_enabled, ...
    'desired_lower_bandwidth', desired_lower_bandwidth, ...
    'actual_lower_bandwidth', actual_lower_bandwidth, ...
    'desired_upper_bandwidth', desired_upper_bandwidth, ...
    'actual_upper_bandwidth', actual_upper_bandwidth, ...
    'notch_filter_frequency', notch_filter_frequency, ...
    'desired_impedance_test_frequency', desired_impedance_test_frequency, ...
    'actual_impedance_test_frequency', actual_impedance_test_frequency );

% Define data structure for spike trigger settings.
spike_trigger_struct = struct( ...
    'voltage_trigger_mode', {}, ...
    'voltage_threshold', {}, ...
    'digital_trigger_channel', {}, ...
    'digital_edge_polarity', {} );

new_trigger_channel = struct(spike_trigger_struct);
spike_triggers = struct(spike_trigger_struct);

% Define data structure for data channels.
channel_struct = struct( ...
    'native_channel_name', {}, ...
    'custom_channel_name', {}, ...
    'native_order', {}, ...
    'custom_order', {}, ...
    'board_stream', {}, ...
    'chip_channel', {}, ...
    'port_name', {}, ...
    'port_prefix', {}, ...
    'port_number', {}, ...
    'electrode_impedance_magnitude', {}, ...
    'electrode_impedance_phase', {} );

new_channel = struct(channel_struct);

% Create structure arrays for each type of data channel.
amplifier_channels = struct(channel_struct);
aux_input_channels = struct(channel_struct);
supply_voltage_channels = struct(channel_struct);
board_adc_channels = struct(channel_struct);
board_dig_in_channels = struct(channel_struct);
board_dig_out_channels = struct(channel_struct);

amplifier_index = 1;
aux_input_index = 1;
supply_voltage_index = 1;
board_adc_index = 1;
board_dig_in_index = 1;
board_dig_out_index = 1;

% Read signal summary from data file header.

number_of_signal_groups = fread(fid, 1, 'int16');

for signal_group = 1:number_of_signal_groups
    signal_group_name = fread_QString(fid);
    signal_group_prefix = fread_QString(fid);
    signal_group_enabled = fread(fid, 1, 'int16');
    signal_group_num_channels = fread(fid, 1, 'int16');
    signal_group_num_amp_channels = fread(fid, 1, 'int16');

    if (signal_group_num_channels > 0 && signal_group_enabled > 0)
        new_channel(1).port_name = signal_group_name;
        new_channel(1).port_prefix = signal_group_prefix;
        new_channel(1).port_number = signal_group;
        for signal_channel = 1:signal_group_num_channels
            new_channel(1).native_channel_name = fread_QString(fid);
            new_channel(1).custom_channel_name = fread_QString(fid);
            new_channel(1).native_order = fread(fid, 1, 'int16');
            new_channel(1).custom_order = fread(fid, 1, 'int16');
            signal_type = fread(fid, 1, 'int16');
            channel_enabled = fread(fid, 1, 'int16');
            new_channel(1).chip_channel = fread(fid, 1, 'int16');
            new_channel(1).board_stream = fread(fid, 1, 'int16');
            new_trigger_channel(1).voltage_trigger_mode = fread(fid, 1, 'int16');
            new_trigger_channel(1).voltage_threshold = fread(fid, 1, 'int16');
            new_trigger_channel(1).digital_trigger_channel = fread(fid, 1, 'int16');
            new_trigger_channel(1).digital_edge_polarity = fread(fid, 1, 'int16');
            new_channel(1).electrode_impedance_magnitude = fread(fid, 1, 'single');
            new_channel(1).electrode_impedance_phase = fread(fid, 1, 'single');

            if (channel_enabled)
                switch (signal_type)
                    case 0
                        amplifier_channels(amplifier_index) = new_channel;
                        spike_triggers(amplifier_index) = new_trigger_channel;
                        amplifier_index = amplifier_index + 1;
                    case 1
                        aux_input_channels(aux_input_index) = new_channel;
                        aux_input_index = aux_input_index + 1;
                    case 2
                        supply_voltage_channels(supply_voltage_index) = new_channel;
                        supply_voltage_index = supply_voltage_index + 1;
                    case 3
                        board_adc_channels(board_adc_index) = new_channel;
                        board_adc_index = board_adc_index + 1;
                    case 4
                        board_dig_in_channels(board_dig_in_index) = new_channel;
                        board_dig_in_index = board_dig_in_index + 1;
                    case 5
                        board_dig_out_channels(board_dig_out_index) = new_channel;
                        board_dig_out_index = board_dig_out_index + 1;
                    otherwise
                        error('Unknown channel type');
                end
            end

        end
    end
end

% Summarize contents of data file.
num_amplifier_channels = amplifier_index - 1;
num_aux_input_channels = aux_input_index - 1;
num_supply_voltage_channels = supply_voltage_index - 1;
num_board_adc_channels = board_adc_index - 1;
num_board_dig_in_channels = board_dig_in_index - 1;
num_board_dig_out_channels = board_dig_out_index - 1;

if options.Verbosity == "high"
    fprintf(1, 'Found %d amplifier channel%s.\n', ...
        num_amplifier_channels, plural(num_amplifier_channels));
    fprintf(1, 'Found %d auxiliary input channel%s.\n', ...
        num_aux_input_channels, plural(num_aux_input_channels));
    fprintf(1, 'Found %d supply voltage channel%s.\n', ...
        num_supply_voltage_channels, plural(num_supply_voltage_channels));
    fprintf(1, 'Found %d board ADC channel%s.\n', ...
        num_board_adc_channels, plural(num_board_adc_channels));
    fprintf(1, 'Found %d board digital input channel%s.\n', ...
        num_board_dig_in_channels, plural(num_board_dig_in_channels));
    fprintf(1, 'Found %d board digital output channel%s.\n', ...
        num_board_dig_out_channels, plural(num_board_dig_out_channels));
    fprintf(1, 'Found %d temperature sensor channel%s.\n', ...
        num_temp_sensor_channels, plural(num_temp_sensor_channels));
    fprintf(1, '\n');
end
% Determine how many samples the data file contains.

% Each data block contains num_samples_per_data_block amplifier samples.
bytes_per_block = num_samples_per_data_block * 4;  % timestamp data
bytes_per_block = bytes_per_block + num_samples_per_data_block * 2 * num_amplifier_channels;
% Auxiliary inputs are sampled 4x slower than amplifiers
bytes_per_block = bytes_per_block + (num_samples_per_data_block / 4) * 2 * num_aux_input_channels;
% Supply voltage is sampled once per data block
bytes_per_block = bytes_per_block + 1 * 2 * num_supply_voltage_channels;
% Board analog inputs are sampled at same rate as amplifiers
bytes_per_block = bytes_per_block + num_samples_per_data_block * 2 * num_board_adc_channels;
% Board digital inputs are sampled at same rate as amplifiers
if (num_board_dig_in_channels > 0)
    bytes_per_block = bytes_per_block + num_samples_per_data_block * 2;
end
% Board digital outputs are sampled at same rate as amplifiers
if (num_board_dig_out_channels > 0)
    bytes_per_block = bytes_per_block + num_samples_per_data_block * 2;
end
% Temp sensor is sampled once per data block
if (num_temp_sensor_channels > 0)
    bytes_per_block = bytes_per_block + 1 * 2 * num_temp_sensor_channels;
end

% How many data blocks remain in this file? Whole blocks only: a truncated
% last block (a recording cut short) is ignored.
data_present = 0;
bytes_remaining = filesize - ftell(fid);
if (bytes_remaining > 0)
    data_present = 1;
end

num_data_blocks = floor(bytes_remaining / bytes_per_block);

num_amplifier_samples = num_samples_per_data_block * num_data_blocks;
num_board_dig_in_samples = num_samples_per_data_block * num_data_blocks;
num_board_dig_out_samples = num_samples_per_data_block * num_data_blocks;

record_time = num_amplifier_samples / sample_rate;

if options.Verbosity == "high"
    if (data_present)
        fprintf(1, 'File contains %0.3f seconds of data.  Amplifiers were sampled at %0.2f kS/s.\n', ...
            record_time, sample_rate / 1000);
        fprintf(1, '\n');
    else
        fprintf(1, 'Header file contains no data.  Amplifiers were sampled at %0.2f kS/s.\n', ...
            sample_rate / 1000);
        fprintf(1, '\n');
    end
end

if (data_present)

    % Read sampled data from file: every data block with one fread, as
    % uint16 words (one block per column), then split into the signals in
    % the order each block holds them (IntanReader.sliceDataBlocks). The
    % timestamps are signed from version 1.2 on (negative, adjusted
    % timestamps for pretrigger data), unsigned before.
    if options.Verbosity == "high"
        fprintf(1, 'Reading data from file...\n');
    end
    raw = fread(fid, [bytes_per_block / 2, num_data_blocks], 'uint16=>uint16');
    layout = struct('numSamplesPerDataBlock', num_samples_per_data_block, ...
        'numAmplifierChannels', num_amplifier_channels, ...
        'numAuxInputChannels', num_aux_input_channels, ...
        'numSupplyVoltageChannels', num_supply_voltage_channels, ...
        'numTempSensorChannels', num_temp_sensor_channels, ...
        'numBoardADCChannels', num_board_adc_channels, ...
        'numBoardDigInChannels', num_board_dig_in_channels, ...
        'numBoardDigOutChannels', num_board_dig_out_channels, ...
        'mainVersion', data_file_main_version_number, ...
        'secondaryVersion', data_file_secondary_version_number);
    B = IntanReader.sliceDataBlocks(raw, layout);
    clear raw

    if options.Verbosity == "high"

        fprintf(1, 'Parsing data...\n');
    end

    t_amplifier = B.timestamps;
    amplifier_data = double(B.amplifier);
    B.amplifier = [];
    aux_input_data = double(B.aux);
    supply_voltage_data = double(B.supply);
    temp_sensor_data = double(B.temp);
    board_adc_data = double(B.adc);

    % Extract digital input channels to separate variables.
    board_dig_in_data = zeros(num_board_dig_in_channels, num_board_dig_in_samples);
    board_dig_out_data = zeros(num_board_dig_out_channels, num_board_dig_out_samples);
    if (num_board_dig_in_channels > 0)
        board_dig_in_data = digital_lines(B.digIn, [board_dig_in_channels.native_order]);
    end
    if (num_board_dig_out_channels > 0)
        board_dig_out_data = digital_lines(B.digOut, [board_dig_out_channels.native_order]);
    end
    clear B

    % Scale voltage levels appropriately.
    amplifier_data = 0.195 * (amplifier_data - 32768); % units = microvolts
    aux_input_data = 37.4e-6 * aux_input_data; % units = volts
    supply_voltage_data = 74.8e-6 * supply_voltage_data; % units = volts
    if (board_mode == 1)
        board_adc_data = 152.59e-6 * (board_adc_data - 32768); % units = volts
    elseif (board_mode == 13) % Intan Recording Controller
        board_adc_data = 312.5e-6 * (board_adc_data - 32768); % units = volts
    else
        board_adc_data = 50.354e-6 * board_adc_data; % units = volts
    end
    temp_sensor_data = temp_sensor_data / 100; % units = deg C

    % Check for gaps in timestamps.
    num_gaps = sum(diff(t_amplifier) ~= 1);


    if (num_gaps == 0)
        if options.Verbosity == "high"

            fprintf(1, 'No missing timestamps in data.\n');
        end
    else
        fprintf(1, 'Warning: %d gaps in timestamp data found.  Time scale will not be uniform!\n', ...
            num_gaps);
    end

    % Scale time steps (units = seconds).
    t_amplifier = t_amplifier / sample_rate;
    t_aux_input = t_amplifier(1:4:end);
    t_supply_voltage = t_amplifier(1:num_samples_per_data_block:end);
    t_board_adc = t_amplifier;
    t_dig = t_amplifier;
    t_temp_sensor = t_supply_voltage;

    % If the software notch filter was selected during the recording, apply the
    % same notch filter to amplifier data here.  But don't do this for v3.0+
    % files (from Intan RHX software) because RHX saves notch-filtered data.
    if (notch_filter_frequency > 0 && data_file_main_version_number < 3)
        if options.Verbosity == "high"

            fprintf(1, 'Applying notch filter...\n');
        end
        print_increment = 10;
        percent_done = print_increment;
        for i=1:num_amplifier_channels
            amplifier_data(i,:) = ...
                notch_filter(amplifier_data(i,:), sample_rate, notch_filter_frequency, 10);
            if options.Verbosity == "high"

                fraction_done = 100 * (i / num_amplifier_channels);
                if (fraction_done >= percent_done)
                    fprintf(1, '%d%% done...\n', percent_done);
                    percent_done = percent_done + print_increment;
                end
            end
        end
    end

end

% Move variables to base workspace.

% new for version 2.01: move filename info to base workspace


[path,filename] = fileparts(ffn);

D = struct('amplifier_channels',struct([]),'amplifier_data',[],'aux_input_channels',struct([]), ...
    'aux_input_data',[],'board_dig_in_channels',struct([]),'board_dig_in_data',[], ...
    'filename','','frequency_parameters',struct([]),'notes',struct([]),'path','', ...
    'reference_channel','','spike_triggers',struct([]),'t_amplifier',[],'t_aux_input',[],'t_dig',[]);
D = move_to_base_workspace(D,filename);
D = move_to_base_workspace(D,path);

D = move_to_base_workspace(D,notes);
D = move_to_base_workspace(D,frequency_parameters);
if (data_file_main_version_number > 1)
    D = move_to_base_workspace(D,reference_channel);
end

if (num_amplifier_channels > 0)
    D = move_to_base_workspace(D,amplifier_channels);
    if (data_present)
        D = move_to_base_workspace(D,amplifier_data);
        D = move_to_base_workspace(D,t_amplifier);
    end
    D = move_to_base_workspace(D,spike_triggers);
end
if (num_aux_input_channels > 0)
    D = move_to_base_workspace(D,aux_input_channels);
    if (data_present)
        D = move_to_base_workspace(D,aux_input_data);
        D = move_to_base_workspace(D,t_aux_input);
    end
end
if (num_supply_voltage_channels > 0)
    D = move_to_base_workspace(D,supply_voltage_channels);
    if (data_present)
        D = move_to_base_workspace(D,supply_voltage_data);
        D = move_to_base_workspace(D,t_supply_voltage);
    end
end
if (num_board_adc_channels > 0)
    D = move_to_base_workspace(D,board_adc_channels);
    if (data_present)
        D = move_to_base_workspace(D,board_adc_data);
        D = move_to_base_workspace(D,t_board_adc);
    end
end
if (num_board_dig_in_channels > 0)
    D = move_to_base_workspace(D,board_dig_in_channels);
    if (data_present)
        D = move_to_base_workspace(D,board_dig_in_data);
        D = move_to_base_workspace(D,t_dig);
    end
end
if (num_board_dig_out_channels > 0)
    D = move_to_base_workspace(D,board_dig_out_channels);
    if (data_present)
        D = move_to_base_workspace(D,board_dig_out_data);
        D = move_to_base_workspace(D,t_dig);
    end
end
if (num_temp_sensor_channels > 0)
    if (data_present)
        D = move_to_base_workspace(D,temp_sensor_data);
        D = move_to_base_workspace(D,t_temp_sensor);
    end
end
if options.Verbosity == "high"

    fprintf(1, 'Done!  Elapsed time: %0.1f seconds\n', toc);
end
% if (data_present)
%     fprintf(1, 'Extracted data are now available in the MATLAB workspace.\n');
% else
%     fprintf(1, 'Extracted waveform information is now available in the MATLAB workspace.\n');
% end
% fprintf(1, 'Type ''whos'' to see variables.\n');
% fprintf(1, '\n');

return


function a = fread_QString(fid)

% a = read_QString(fid)
%
% Read Qt style QString.  The first 32-bit unsigned number indicates
% the length of the string (in bytes).  If this number equals 0xFFFFFFFF,
% the string is null.

a = '';
length = fread(fid, 1, 'uint32');
if length == hex2num('ffffffff')
    return;
end
% convert length from bytes to 16-bit Unicode words
length = length / 2;

for i=1:length
    a(i) = fread(fid, 1, 'uint16');
end

return


function s = plural(n)

% s = plural(n)
%
% Utility function to optionally plurailze words based on the value
% of n.

if (n == 1)
    s = '';
else
    s = 's';
end

return


function out = notch_filter(in, fSample, fNotch, Bandwidth)

% out = notch_filter(in, fSample, fNotch, Bandwidth)
%
% Implements a notch filter (e.g., for 50 or 60 Hz) on vector 'in'.
% fSample = sample rate of data (in Hz or Samples/sec)
% fNotch = filter notch frequency (in Hz)
% Bandwidth = notch 3-dB bandwidth (in Hz).  A bandwidth of 10 Hz is
%   recommended for 50 or 60 Hz notch filters; narrower bandwidths lead to
%   poor time-domain properties with an extended ringing response to
%   transient disturbances.
%
% Example:  If neural data was sampled at 30 kSamples/sec
% and you wish to implement a 60 Hz notch filter:
%
% out = notch_filter(in, 30000, 60, 10);

tstep = 1/fSample;
Fc = fNotch*tstep;

L = length(in);

% Calculate IIR filter parameters
d = exp(-2*pi*(Bandwidth/2)*tstep);
b = (1 + d*d)*cos(2*pi*Fc);
a0 = 1;
a1 = -b;
a2 = d*d;
a = (1 + d*d)/2;
b0 = 1;
b1 = -2*cos(2*pi*Fc);
b2 = 1;

out = zeros(size(in));
out(1) = in(1);
out(2) = in(2);
% (If filtering a continuous data stream, change out(1) and out(2) to the
%  previous final two values of out.)

% Run filter
for i=3:L
    out(i) = (a*b2*in(i-2) + a*b1*in(i-1) + a*b0*in(i) - a2*out(i-2) - a1*out(i-1))/a0;
end

return


function data = digital_lines(words, orders)

% data = digital_lines(words, orders)
%
% [numel(orders) x numel(words)] double 0/1: row i is 1 where bit orders(i)
% of the 16-bit digital WORDS is set. Each line is tested on the uint16
% words as a column and the result transposed once, which gives the values
% the row-by-row test on double words gives, ~25x faster; a native_order a
% 16-bit word cannot hold keeps that original row-by-row test.

if all(orders >= 0 & orders < 16 & orders == round(orders))
    lines = false(numel(words), numel(orders));
    w = words(:);
    for i = 1:numel(orders)
        lines(:, i) = bitand(w, uint16(2^orders(i))) > 0;
    end
    data = double(lines.');
else
    raw = double(words);
    data = zeros(numel(orders), numel(words));
    for i = 1:numel(orders)
        mask = 2^(orders(i)) * ones(size(raw));
        data(i, :) = (bitand(raw, mask) > 0);
    end
end

return


function D = move_to_base_workspace(D,variable)

% D = move_to_base_workspace(D,variable)
%
% Move variable from function workspace to base MATLAB workspace so
% user will have access to it after the program ends.

variable_name = inputname(2);

D.(variable_name) = variable;



