function s = defaults(section)
%defaults  Default settings of one config section (schema v1).
%   S = EphysPipelineConfig.defaults("Spikes") etc. The defaults are the
%   single source of truth for field names, types and shapes: normalizeSection
%   coerces every assigned value to match them.
%
%   Continuous-signal defaults mirror EphysDataset.deriveSignals; detection
%   defaults mirror EphysDataset.detectSpikes; the artifact defaults come from
%   EphysDataset.defaultArtifactConfig.

arguments
    section (1,1) string
end

switch section
    case "Project"
        s = struct( ...
            'Root',       "", ...            % folder scanned for recordings
            'Recursive',  true, ...          % search every sub-folder; false = Root and the folders directly in it
            'OutputRoot', "", ...            % "" = outputs next to each recording
            'Selection',  "all", ...         % "all" | "list"
            'Datasets',   string.empty(1,0), ... % root-relative keys when "list"
            'NamePattern',  EphysDataset.DefaultNamePattern, ... % see parseNameTokens; labels sorted units
            'TokenColumns', "SubjectID");     % list text: tokens shown as dataset-table columns

    case "Acquisition"
        % Reader options (EphysReader): each reader reads its own sub-struct.
        s = struct( ...
            'OpenEphys', struct( ...
                'Recordings', "concatenate", ... % "concatenate" | "separate" | "single": several recordings in one session
                'RecordNode', "", ...            % Record Node id ("" = the only one; the lowest id when several)
                'Stream',     ""));              % continuous stream ("" = the one with the most headstage channels)

    case "Parallel"
        s = struct( ...
            'Enabled',    false, ...  % artifacts + spike detection chunks on a process pool
            'MaxWorkers', NaN);       % cap on chunks in flight; NaN = from free memory

    case "Probe"
        s = struct( ...
            'DefaultProbeFile',       "", ...  % assigned to datasets without a probe
            'WriteDefaultToManifest', false);

    case "Behavior"
        s = struct( ...
            'Enabled',           false, ...
            'SearchDirs',        string.empty(1,0), ...
            'Match',             "prefix-then-time", ...  % "prefix" | "time" | "prefix-then-time"
            'MaxStartOffsetMin', 30, ...
            'Overwrite',         false, ...   % re-match datasets that already have a file
            'WriteFile',         true, ...    % save <Name>_behavior.mat for associated datasets
            'PairTrials',        true, ...    % pair trials in order with TrialLine intervals (needs review)
            'AutoApprove',       false, ...   % approve a pairing whose trial / interval counts match without cuts
            'TrialLine',         "InTrial");  % digital line that is on during each trial

    case "Artifacts"
        a = EphysDataset.defaultArtifactConfig();
        s = struct( ...
            'Reference',        a.Reference, ...        % "none" | "car" | "cmr": common reference, before detection
            'ReferenceBadLow',  a.ReferenceBadLow, ...  % suggested out of the reference below this x median noise
            'ReferenceBadHigh', a.ReferenceBadHigh, ... % ... and above this
            'Enabled',        false, ...       % automatic detection (manual periods always apply)
            'Method',         a.Method, ...
            'Threshold',      a.Threshold, ...
            'RmsWindowMs',    a.RmsWindowMs, ...
            'MergeGapMs',     a.MergeGapMs, ...
            'MinChannels',    a.MinChannels, ...
            'PadMs',          a.PadMs, ...
            'Filter',         a.Filter, ...
            'FilterType',     a.FilterType, ...
            'FilterCutoff',   a.FilterCutoff, ...
            'FilterOrder',    a.FilterOrder, ...
            'Fill',           a.Fill, ...          % erase artifacts with noise or zeros
            'NoiseBandHz',    a.NoiseBandHz, ...   % band the noise level is measured in
            'NoiseSeed',      a.NoiseSeed, ...     % RNG seed for the fill
            'ApplyToSorting', true, ...        % automatic periods too (manual ones always apply)
            'ApplyToSpikes',  true, ...
            'ApplyToSignals', true, ...
            'CacheIntervals', true);

    case "Sorting"
        ks4 = struct();
        spec = EphysPipelineConfig.kilosortParamSpec();
        for i = 1:numel(spec)
            ks4.(spec(i).name) = ks4Default(spec(i));
        end
        s = struct( ...
            'Enabled',      false, ...
            'PythonExe',    "", ...
            'CondaEnv',     "", ...
            'Execution',    "background", ...  % "background" | "blocking"
            'MaxConcurrent', 1, ...             % background runs at once; the rest wait for a free slot
            'Devices',      string.empty(1,0), ...   % torch devices shared out ("cuda:0" "cuda:1"); none = Kilosort4's choice
            'DryRun',       false, ...
            'SkipExisting', false, ...          % skip datasets that already have results
            'KS4',          ks4, ...
            'KS4ExtraJSON', "");

    case "Signals"
        s = struct( ...
            'Enabled',            false, ...
            'OutputDir',          "", ...
            'Suffix',             "_extract", ...
            'SeparateFiles',      true, ...    % one <Name><Suffix>_<TYPE>.mat per signal type
            'MatVersion',         "-v7.3", ...
            'Overwrite',          false, ...
            'LFP',                true, ...
            'MUA',                false, ...
            'SPIKE',              false, ...
            'AUX',                false, ...   % aux (accelerometer) inputs, when recorded
            'BlankArtifacts',     true, ...    % erase the artifact periods before deriving; recorded in every file
            'LFP_Reference',      false, ...   % subtract the common reference (Artifacts.Reference) from the LFP
            'MUA_Reference',      true, ...    % ... from the MUA
            'SPIKE_Reference',    true, ...    % ... from the SPIKE band
            'LFP_Fs',             1000, ...
            'LFP_HighpassOn',     false, ...
            'LFP_HighpassHz',     1, ...
            'LFP_LowpassOn',      false, ...
            'LFP_LowpassHz',      300, ...
            'LFP_NotchOn',        false, ...
            'LFP_NotchHz',        "60", ...    % list text, e.g. "60, 120, 180"
            'LFP_NotchBW',        2, ...
            'MUA_Fs',             2000, ...
            'MUA_IntegrationHz',  1000, ...
            'MUA_bpLoHi',         [300 5000], ...
            'SPIKE_KeepOriginal', true, ...
            'SPIKE_Fs',           20000, ...   % used only when KeepOriginal is off
            'SPIKE_bpLoHi',       [300 5000], ...
            'LabelField',         "custom", ...  % "custom" | "native": channel, aux and digital-line names
            'LineNames',          string.empty(1,0), ...  % "native=name" digital-line names, e.g. "TTL4=InTrial"
            'InvertedLines',      string.empty(1,0), ...  % digital lines on while low (onset = falling edge)
            'KeepChannels',       "", ...
            'BadMode',            "none", ...  % "none" | "manual" | "auto"
            'BadThreshold',       3, ...
            'BadList',            "", ...
            'ChannelRemap',       "", ...
            'ExcludeHandling',    "none");     % "none" | "drop" | "interpolate" (manifest exclusions)

    case "Spikes"
        s = struct( ...
            'Enabled',         false, ...
            'Source',          "detect", ...   % "detect" | "sorted" | "both"
            'Filter',          true, ...
            'Band',            [500 5000], ...
            'FilterOrder',     4, ...
            'Polarity',        "negative", ...
            'ThresholdMethod', "mad", ...
            'Threshold',       NaN, ...        % NaN = detectSpikes' default for the method
            'Align',           "trough", ...
            'AlignWindowMs',   1, ...
            'MinPeriodMs',     1, ...
            'MaxAmplitudeUV',  Inf, ...
            'Waveforms',       false, ...
            'WindowMs',        [-0.5 1.5], ...
            'WaveformSource',  "filtered", ...
            'EdgeHandling',    "nan", ...
            'Channels',        "all", ...      % "all" | "excludeManifest" | "list"
            'ChannelList',     "", ...
            'ArtifactMode',    "reject", ...   % artifact periods: "reject" the events in them | "erase" them before detection | "none"
            'MaxChunkSamples', NaN, ...
            'EdgePadMs',       NaN, ...
            'Groups',          ["good" "mua"], ...
            'IncludeNoise',    false, ...
            'Templates',       true, ...
            'OutputDir',       "", ...
            'Suffix',          "_spikes", ...
            'MatVersion',      "-v7.3", ...
            'Overwrite',       false);

    case "Export"
        s = struct( ...
            'Enabled',         false, ...
            'Formats',         string.empty(1,0), ...   % subset of EphysPipelineConfig.ExportFormats
            'Signals',         string.empty(1,0), ...   % [] = every signal in the extract
            'IncludeUnits',    true, ...
            'IncludeDetected', false, ...
            'IncludeEvents',   true, ...
            'Groups',          ["good" "mua"], ...
            'Validate',        true, ...
            'EpochSource',     "line", ...      % "line" (dig-in events) | "behavior" (paired trials)
            'EpochLine',       "", ...          % dig-in line ("" = Behavior.TrialLine, else the only line)
            'EpochWindow',     [-0.2 0.5], ...  % [tPre tPost] seconds around each onset
            'EpochOnsetRule',  "event", ...     % "event" | "sample" (ChronuxDataset.trials)
            'EpochIncomplete', "nan", ...       % window past the recording: "nan" | "drop" | "error"
            'EpochNonFinite',  "keep", ...      % epoch with NaN/Inf samples: "keep" | "drop" | "error"
            'EpochArtifacts',  "drop", ...      % epoch touching an artifact period of the extract: "drop" | "keep"
            'EpochSpikeTimeBase', "onset", ...  % "onset" | "window" | "absolute"
            'EpochClass',      "double", ...    % "double" | "single" | "asis"
            'OutputDir',       "", ...
            'MatVersion',      "-v7.3", ...
            'Overwrite',       false);

    otherwise
        error('EphysPipelineConfig:BadSection', 'Unknown section "%s".', section);
end
end


function v = ks4Default(p)
%ks4Default  Typed default of one Kilosort4 parameter (see kilosortParamSpec).
switch p.kind
    case 'bool',     v = logical(p.default);
    case {'int', 'float'}, v = double(p.default);
    case 'floatinf'
        [v, ~] = EphysPipelineConfig.ks4ParamFromText('floatinf', p.default);
    case 'nullable'
        [v, ~] = EphysPipelineConfig.ks4ParamFromText('nullable', p.default);
    case 'vector'
        [v, ~] = EphysPipelineConfig.ks4ParamFromText('vector', p.default);
    otherwise
        v = p.default;
end
end
