function cfg = defaultConvertConfig(~)
    % Convert-tab defaults. The signal options mirror the defaults
    % of EphysDataset.deriveSignals (= intan2matlab): dataTypeOut
    % "LFP", LFP_Fs 1000, no LFP filtering (LFP_bpLoHi [0 Inf], no
    % notch), MUA_Fs 2000, MUA_IntegrationHz 1000, band edges
    % [300 5000], SPIKE_Fs Inf, labelField custom_channel_name, no
    % channel selection / bad channels / remap. The LFP cut-off /
    % notch values below are only used once their box is ticked.
    % OutputDir "" = each dataset's folder.
    cfg = struct( ...
        'OutputDir',          "", ...
        'Suffix',             "_extract", ...
        'MatVersion',         "-v7.3", ...
        'Overwrite',          false, ...
        'LFP',                true, ...
        'MUA',                false, ...
        'SPIKE',              false, ...
        'LFP_Fs',             1000, ...
        'LFP_HighpassOn',     false, ...
        'LFP_HighpassHz',     1, ...
        'LFP_LowpassOn',      false, ...
        'LFP_LowpassHz',      300, ...
        'LFP_NotchOn',        false, ...
        'LFP_NotchHz',        "60", ...    % list text, e.g. "60, 120, 180"
        'LFP_NotchBW',        2, ...
        'MUA_Fs',             2000, ...
        'MUA_IntegrationHz',  1000, ...
        'MUA_bpLoHi',         [300 5000], ...
        'SPIKE_KeepOriginal', true, ...
        'SPIKE_Fs',           20000, ...   % used only when KeepOriginal is off
        'SPIKE_bpLoHi',       [300 5000], ...
        'LabelField',         "custom_channel_name", ...
        'KeepChannels',       "", ...
        'BadMode',            "none", ...  % "none" | "manual" | "auto"
        'BadThreshold',       3, ...       % auto: |zscore(RMS)| threshold
        'BadList',            "", ...
        'ChannelRemap',       "");
end
