function savePreferences(obj)
%savePreferences  Persist app preferences (not the pipeline config).
%   See loadPreferences for the list. The config itself is saved through
%   File > Save; only its file name is remembered here.

g = obj.PrefGroup;
if isvalid(obj.Fig)
    setpref(g, 'FigurePosition', obj.Fig.Position);
end
setpref(g, 'ProbeFolder',   char(obj.ProbeFolderField.Value));
setpref(g, 'PhyCmd',        char(obj.PhyCmdField.Value));
setpref(g, 'ReviewFolder',  char(obj.ReviewFolderField.Value));
setpref(g, 'ScriptFolder',  char(obj.ScriptFolder));
setpref(g, 'RecentConfigs', cellstr(obj.RecentConfigs));
setpref(g, 'LastConfigFile', char(obj.Config.File));
setpref(g, 'VizOptions', struct( ...
    'channels',  char(obj.VizChannelsField.Value), ...
    'duration',  obj.VizDurField.Value, ...
    'highpass',  char(obj.VizHighpassField.Value), ...
    'lowpass',   char(obj.VizLowpassField.Value), ...
    'order',     obj.VizOrderField.Value, ...
    'reference', char(obj.VizRefDropDown.Value), ...
    'detrend',   logical(obj.VizDetrendCheckBox.Value), ...
    'spacing',   obj.VizSpacingField.Value));
end
